__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader_regnet.yml',
  './include/optimizer_regnet.yml',
  './include/stqsdetr_regnet.yml',
]

output_dir: ./output/stqsdetr_regnet_6x_coco

